"""7D ISORROPIA LUT for thermodynamic gas/particle partitioning.

Wraps a pre-computed lookup table generated by HETP (metastable ISORROPIA II).
7 axes: total_SO4 (S ug/m3), total_NH (N ug/m3), total_NO3 (N ug/m3),
        crustal_Ca (Ca ug/m3), sea_salt_Na (Na ug/m3), T (K), RH (0-1).
4 outputs: f_nh4, f_no3, aerosol_water (ug/m3), pH.
"""

import numpy as np
from scipy.interpolate import RegularGridInterpolator


class IsorropiaLUT:
    """Query interface for the 7D ISORROPIA lookup table."""

    def __init__(self, lut_path, fields=("f_nh4", "f_no3")):
        """Load the 7D LUT.

        ``fields`` restricts which output fields are loaded into memory.
        The default loads only the two fields the partitioning closure uses
        (f_nh4, f_no3) — production never consumes aerosol_water/ph, and
        loading all 4 wastes ~1.7 GB.  Pass
        ``fields=("f_nh4", "f_no3", "aerosol_water", "ph")`` to load all 4;
        ``query()`` returns NaN for any field not loaded.

        NB: we intentionally keep the table as float32 (its on-disk
        dtype) rather than upcasting to float64.  scipy's
        RegularGridInterpolator handles mixed-precision evaluation
        correctly, and the upcast would double memory from 3.4 GB to
        6.9 GB — breaking 8 GB budgets on compute nodes.
        """
        self._path = str(lut_path)
        self._fields = tuple(fields)
        self._interp = None
        self.axes = None
        self.n_loads = 0
        self.load_seconds = 0.0
        # The table is read on the first query, not here: a forward run
        # constructs it before the baseline solve, whose LU factors set the
        # run's peak memory, and the first query comes after that solve.
        self._cache_dir = self._cache_location()

    _AXES = ("so4_axis", "nh_axis", "no3_axis", "ca_axis", "na_axis", "t_axis", "rh_axis")

    def _cache_location(self):
        """Directory holding the decompressed fields, or None.

        Reloading the fields from the compressed archive costs about a
        minute each time; from plain .npy files next to it (or under
        ORBIT_LUT_CACHE_DIR) it costs seconds. The cache is written on the
        first load and keyed by the archive's size and modification time.
        """
        import os
        base = os.environ.get("ORBIT_LUT_CACHE_DIR") or (self._path + ".cache")
        try:
            st = os.stat(self._path)
        except OSError:
            return None
        return os.path.join(base, f"{st.st_size}_{int(st.st_mtime)}")

    def _load(self):
        """Read the axes and the requested fields into memory."""
        import os, time
        t0 = time.time()
        data = None
        cached = (self._cache_dir is not None
                  and os.path.exists(os.path.join(self._cache_dir, "complete"))
                  and all(os.path.exists(os.path.join(self._cache_dir, f"{n}.npy"))
                          for n in self._AXES + self._fields))
        if cached:
            arrays = {n: np.load(os.path.join(self._cache_dir, f"{n}.npy"))
                      for n in self._AXES + self._fields}
        else:
            data = np.load(self._path)
            arrays = {n: data[n] for n in self._AXES + self._fields}
            if self._cache_dir is not None:
                try:
                    os.makedirs(self._cache_dir, exist_ok=True)
                    for n, a in arrays.items():
                        np.save(os.path.join(self._cache_dir, f"{n}.npy"), a)
                    open(os.path.join(self._cache_dir, "complete"), "w").close()
                except OSError:
                    pass   # read-only location: reload from the archive next time
        axes = tuple(arrays[n] for n in self._AXES)
        self._interp = {}
        for name in self._fields:
            self._interp[name] = RegularGridInterpolator(
                axes,
                arrays[name],  # keep as float32 — saves ~1.7 GB per field
                bounds_error=False,
                fill_value=None,  # linear extrapolation; outputs clamped in query()
            )
        self.axes = axes
        self.n_loads += 1
        self.load_seconds += time.time() - t0

    @property
    def loaded(self):
        return self._interp is not None

    def release(self):
        """Drop the table from memory; the next query reloads it.

        The closure queries the table once per outer iteration and the
        forward solves in between hold the LU factors that set the run's
        peak memory. Releasing the 1.8 GB of table after each query keeps
        it out of that peak (memory audit of 2026-08-01, fix 2); a reload
        from the compressed archive costs a few seconds.
        """
        self._interp = None

    def _ensure_loaded(self):
        if self._interp is None:
            self._load()

    def query(self, total_so4, total_nh, total_no3, crustal_ca, sea_salt_na, T, RH):
        """Query the 7D LUT.

        All concentrations in ug/m3 (element mass). T in K. RH in 0-1.
        crustal_ca and sea_salt_na can be 0 for cells without dust/sea-salt.

        Inputs can be scalars or arrays of the same shape.
        Returns (f_nh4, f_no3, aerosol_water, ph) as arrays.
        """
        self._ensure_loaded()
        pts = np.column_stack([
            np.atleast_1d(total_so4).ravel(),
            np.atleast_1d(total_nh).ravel(),
            np.atleast_1d(total_no3).ravel(),
            np.atleast_1d(crustal_ca).ravel(),
            np.atleast_1d(sea_salt_na).ravel(),
            np.atleast_1d(T).ravel(),
            np.atleast_1d(RH).ravel(),
        ])
        f_nh4 = np.clip(self._interp["f_nh4"](pts), 0.0, 1.0)
        f_no3 = np.clip(self._interp["f_no3"](pts), 0.0, 1.0)
        # aerosol_water / ph are optional: if the LUT was loaded with only
        # (f_nh4, f_no3) to save memory, return NaN for the missing fields.
        if "aerosol_water" in self._interp:
            awater = np.maximum(self._interp["aerosol_water"](pts), 0.0)
        else:
            awater = np.full_like(f_nh4, np.nan)
        if "ph" in self._interp:
            ph = self._interp["ph"](pts)
        else:
            ph = np.full_like(f_nh4, np.nan)
        return f_nh4, f_no3, awater, ph
