"""7D ISORROPIA LUT for thermodynamic gas/particle partitioning.

Wraps a pre-computed lookup table generated by HETP (metastable ISORROPIA II).
7 axes: total_SO4 (S ug/m3), total_NH (N ug/m3), total_NO3 (N ug/m3),
        crustal_Ca (Ca ug/m3), sea_salt_Na (Na ug/m3), T (K), RH (0-1).
4 outputs: f_nh4, f_no3, aerosol_water (ug/m3), pH.
"""

import numpy as np
from scipy.interpolate import RegularGridInterpolator


class IsorropiaLUT:
    """Query interface for the 7D ISORROPIA lookup table."""

    def __init__(self, lut_path, fields=("f_nh4", "f_no3")):
        """Load the 7D LUT.

        ``fields`` restricts which output fields are loaded into memory.
        The default loads only the two fields the partitioning closure uses
        (f_nh4, f_no3) — production never consumes aerosol_water/ph, and
        loading all 4 wastes ~1.7 GB.  Pass
        ``fields=("f_nh4", "f_no3", "aerosol_water", "ph")`` to load all 4;
        ``query()`` returns NaN for any field not loaded.

        NB: we intentionally keep the table as float32 (its on-disk
        dtype) rather than upcasting to float64.  scipy's
        RegularGridInterpolator handles mixed-precision evaluation
        correctly, and the upcast would double memory from 3.4 GB to
        6.9 GB — breaking 8 GB budgets on compute nodes.
        """
        data = np.load(lut_path)
        axes = (
            data["so4_axis"],
            data["nh_axis"],
            data["no3_axis"],
            data["ca_axis"],
            data["na_axis"],
            data["t_axis"],
            data["rh_axis"],
        )
        self._interp = {}
        for name in fields:
            self._interp[name] = RegularGridInterpolator(
                axes,
                data[name],  # keep as float32 — saves ~1.7 GB per field
                bounds_error=False,
                fill_value=None,  # linear extrapolation; outputs clamped in query()
            )
        self.axes = axes

    def query(self, total_so4, total_nh, total_no3, crustal_ca, sea_salt_na, T, RH):
        """Query the 7D LUT.

        All concentrations in ug/m3 (element mass). T in K. RH in 0-1.
        crustal_ca and sea_salt_na can be 0 for cells without dust/sea-salt.

        Inputs can be scalars or arrays of the same shape.
        Returns (f_nh4, f_no3, aerosol_water, ph) as arrays.
        """
        pts = np.column_stack([
            np.atleast_1d(total_so4).ravel(),
            np.atleast_1d(total_nh).ravel(),
            np.atleast_1d(total_no3).ravel(),
            np.atleast_1d(crustal_ca).ravel(),
            np.atleast_1d(sea_salt_na).ravel(),
            np.atleast_1d(T).ravel(),
            np.atleast_1d(RH).ravel(),
        ])
        f_nh4 = np.clip(self._interp["f_nh4"](pts), 0.0, 1.0)
        f_no3 = np.clip(self._interp["f_no3"](pts), 0.0, 1.0)
        # aerosol_water / ph are optional: if the LUT was loaded with only
        # (f_nh4, f_no3) to save memory, return NaN for the missing fields.
        if "aerosol_water" in self._interp:
            awater = np.maximum(self._interp["aerosol_water"](pts), 0.0)
        else:
            awater = np.full_like(f_nh4, np.nan)
        if "ph" in self._interp:
            ph = self._interp["ph"](pts)
        else:
            ph = np.full_like(f_nh4, np.nan)
        return f_nh4, f_no3, awater, ph
